def main():
    print("Hello , World !")
    print("《神女劈观》")
    print("可——叹——")
    print("秋鸿折单复难双")
    print("痴人痴怨恨迷狂")
    print("只因那邪牲祭伏定祸殃")
    print("若非巾帼拔剑人皆命丧")
    print("凡缘朦朦仙缘滔")
    print("天伦散去绛府邀")
    print("朱丝缚绝烂柯樵")
    print("雪泥鸿迹遥")
    print("鹤归不见昔华表")
    print("蛛丝枉结魂幡飘")
    print("因果红尘渺渺 烟消")
    print("《神女劈观》到这里本该接近尾声，但今日我再添一笔——")
    print("唱与——诸位——听——")
    print("曲高未必人不识")
    print("自有知音和清词")
    print("红缨猎猎剑流星")
    print("直指怒潮洗海清")
    print("彼时鹤归 茫茫天地无依靠 孤身离去")
    print("今日再会 新朋旧友坐满堂 共聚此时")

if __name__ == '__main__':
    main()